### ISSUE TITLE
Images upload to Imgur still probems!

### ISSUE THREAD

**Issue by nguyenrom** [arhangelsoft/image-uploader#1]
I have tried to use v1.3.1 and 1.3.2 beta, but its still problem!

**Comment by arhangelsoft** [comment]
Currently I can build only 1.3.1 from sources, today I'll made release with fixed scripts, that's will work with 1.3.1.
1.3.2 still try to build it without full list of used libraries and sources :(

**Comment by arhangelsoft** [comment]
Fixed in my [latest release](https://github.com/arhangelsoft/image-uploader/releases/latest)
