### ISSUE TITLE
Не загружается на imgur.com 

### ISSUE THREAD

**Issue by EngineExt** [arhangelsoft/image-uploader#3]
`[11:42:54] 
NetworkClient.cpp:434

Request to the URL 'https://api.imgur.com/3/image' failed. 
Response code: 403

{"data":{"error":"Invalid client_id","request":"\/3\/image","method":"POST"},"success":false,"status":403}
g,kK�hhC��b	��ea���UH�R�%�*��"#aY�E�$4�ϳ�r �!,q9Џ\��ю"rFL��Oq��)�Y��u=�
7
b�&�c�#�g<|:�4B�f�F�Ɩ�KHz$2u����h�*�Ue�]a�'p�7�����.V��eQ�;��LQ�_���n��h����B����J௓'!U&�d/����@�\�\(LX¥�E�`Ӯea�S�t®�\��>�>s`��v�,��}}Ӹ^ё����%���/�u�K$�EF��)!S�&E����x�9�+������1��Q�T`

**Comment by arhangelsoft** [comment]
Исправлено уже. Смотрите последний релиз.
